[[custom_groups]]
name = '☯ AdJust'
type = "select"
rule = ['[]☀️ DIRECT', '[]🍭 Proxy', '[]🪻 Residential', '[]💐 HongKong', '[]🏵 Singapore', '[]🌸 Japan', '[]🍉 Korea', '[]🌺 SelfHost', '[]🌹 U.S.', '^(?!.*自建\s+\|).*?[1-9]\.\dx$']

[[custom_groups]]
name = '💧 Telegram'
type = "select"
rule = ['[]🏵 Singapore', '[]💐 HongKong', '[]🪻 Residential', '[]🌸 Japan', '[]🍉 Korea', '[]🌺 SelfHost', '[]🌹 U.S.', '[]🍭 Proxy','^(?!.*自建\s+\|).*?(新加坡|SGP).*?[x\d\)]$','[]☀️ DIRECT']

[[custom_groups]]
name = '🌌 Assistant'
type = "select"
rule = ['[]🪻 Residential', '[]🌺 SelfHost', '[]🏵 Singapore', '[]🌹 U.S.', '[]🍉 Korea', '[]🌸 Japan', '[]🍭 Proxy', '^(?!.*自建\s+\|)(GPT.*?[\dx\]]$|.*?(新加坡|SGP).*?[x\d\)]$|.*?(美国|USA).*?[x\d\)]$|.*?(日本|JP).*?[x\d\)]$)']

[[custom_groups]]
name = '𝕏 Twitter'
type = "select"
rule = ['[]🪻 Residential', '[]💐 HongKong', '[]🏵 Singapore', '[]🌺 SelfHost', '[]🌹 U.S.', '[]🍉 Korea', '[]🌸 Japan', '[]🍭 Proxy', '^(?!.*自建\s+\|)(GPT.*?[\dx\]]$|.*?(香港|HK).*?[x\d\)]$|.*?(新加坡|SGP).*?[x\d\)]$|.*?(美国|USA).*?[x\d\)]$|.*?(日本|JP).*?[x\d\)]$)']

[[custom_groups]]
name = '🍭 Proxy'
type = "select"
rule = ['[]💐 HongKong', '[]🪻 Residential', '[]🏵 Singapore', '[]🌸 Japan', '[]🍉 Korea', '[]🌺 SelfHost', '[]🌹 U.S.', '[]☀️ DIRECT', '^(?!.*自建\s+\|)[^\d].*']

[[custom_groups]]
name = '🧩 Manual'
type = "select"
rule = ['[]🪻 Residential', '[]💐 HongKong', '[]🏵 Singapore', '[]🌺 SelfHost', '[]🌸 Japan', '[]🍉 Korea', '[]🌹 U.S.', '[]☀️ DIRECT', '[]🍭 Proxy', '^(?!.*自建\s+\|).*((香港|HK)|(新加坡|SGP)).*?[x\d\)]$']

[[custom_groups]]
name = '⚡️ Google'
type = "select"
rule = ['[]💐 HongKong', '[]🪻 Residential', '[]🍉 Korea', '[]🌸 Japan', '[]🏵 Singapore', '[]🌺 SelfHost', '[]🌹 U.S.', '[]🍭 Proxy', '^(?!.*自建\s+\|)[^\d冷].*']

[[custom_groups]]
name = '✨ YouTube'
type = "select"
rule = ['[]💐 HongKong', '[]🪻 Residential', '[]🏵 Singapore', '[]🌸 Japan', '[]🍉 Korea', '[]🌺 SelfHost', '[]🌹 U.S.', '[]🍭 Proxy', '^(?!.*自建\s+\|)[^\d冷].*', '[]☀️ DIRECT']

# [[custom_groups]]
# name = '🏖 OpenAI'
# type = "select"
# rule = ['[]🏵 Singapore', '[]🍀 Taiwan', '[]🍉 Korea', '[]🌹 U.S.', '[]🌸 Japan', '[]🍭 Proxy', '(GPT.*?[\dx\]]$|新加坡.*?[x\d\)]$|SGP.*?[x\d\)]$|台湾.*?[x\d\)]$|TW.*?[x\d\)]$|美国.*?[x\d\)]$|USA.*?[x\d\)]$|日本.*?[x\d\)]$|JP.*?[x\d\)]$)']

# [[custom_groups]]
# name = '♊️ Gemini'
# type = "select"
# rule = ['[]🏵 Singapore', '[]🌹 U.S.', '[]🍀 Taiwan', '[]🍉 Korea', '[]🌸 Japan', '[]🍭 Proxy', '(GPT.*?[\dx\]]$|新加坡.*?[x\d\)]$|SGP.*?[x\d\)]$|台湾.*?[x\d\)]$|TW.*?[x\d\)]$|美国.*?[x\d\)]$|USA.*?[x\d\)]$|日本.*?[x\d\)]$|JP.*?[x\d\)]$)']

[[custom_groups]]
name = '💫 FCM'
type = "select"
rule = ['[]☀️ DIRECT', '[]🍭 Proxy', '[]💐 HongKong', '[]🪻 Residential', '[]🍉 Korea', '[]🌸 Japan', '[]🏵 Singapore', '[]🌺 SelfHost', '[]🌹 U.S.', '^(?!.*自建\s+\|)[^\d冷].*']

[[custom_groups]]
name = '🌟 GlobalMedia'
type = "select"
rule = ['[]🍭 Proxy', '[]🪻 Residential', '[]☀️ DIRECT', '^(?!.*自建\s+\|)[^\d冷].*']

[[custom_groups]]
name = '🌎 Others'
type = "select"
rule = ['[]🍭 Proxy', '[]☀️ DIRECT', '^(?!.*自建\s+\|)[^\d冷].*']

[[custom_groups]]
name = '🌺 SelfHost'
type = "select"
rule = ['.*自建\s+\|.*']

[[custom_groups]]
name = '🌹 U.S.'
type = "select"
rule = ['[]🌹 url-test', '^(?!.*自建\s+\|).*?(美国|USA).*?[x\d\)]$']

# [[custom_groups]]
# name = '🍔 U.S.'
# type = "select"
# rule = ['[]🍔 url-test', '(美国.*0\.\d|USA.*0\.\d)']

[[custom_groups]]
name = '💐 HongKong'
type = "select"
rule = ['[]💐 url-test', '^(?!.*自建\s+\|)(?!.*枫\s*\|\s*香港\s+HKBN\b).*?(香港|HK).*?[x\d\)]$']

[[custom_groups]]
name = '🪻 Residential'
type = "select"
rule = ['[]🪻 url-test', '^(?!.*自建\s+\|).*枫\s*\|\s*香港\s+HKBN\b.*?[x\d\)]$']

# [[custom_groups]]
# name = '🥮 HongKong'
# type = "select"
# rule = ['[]🥮 url-test', '(香港.*0\.\d|HK.*0\.\d)']

# [[custom_groups]]
# name = '🍀 Taiwan'
# type = "select"
# rule = ['[]🍀 url-test', '^(?!.*自建\s+\|).*?(台湾|TW).*?[x\d\)]$']

# [[custom_groups]]
# name = '🥠 Taiwan'
# type = "select"
# rule = ['[]🥠 url-test', '(台湾.*0\.\d|TW.*0\.\d)']

[[custom_groups]]
name = '🏵 Singapore'
type = "select"
rule = ['[]🏵 url-test', '^(?!.*自建\s+\|).*?(新加坡|SGP).*?[x\d\)]$']

# [[custom_groups]]
# name = '🍛 Singapore'
# type = "select"
# rule = ['[]🍛 url-test', '(新加坡.*0\.\d|SGP.*0\.\d)']

[[custom_groups]]
name = '🌸 Japan'
type = "select"
rule = ['[]🌸 url-test', '^(?!.*自建\s+\|).*?(日本|JP).*?[x\d\)]$']

# [[custom_groups]]
# name = '🍣 Japan'
# type = "select"
# rule = ['[]🍣 url-test', '(日本.*0\.\d|JP.*0\.\d)']

[[custom_groups]]
name = '🍉 Korea'
type = "select"
rule = ['[]🍉 url-test', '^(?!.*自建\s+\|).*?(韩国|KR).*?[x\d\)]$']

# [[custom_groups]]
# name = '🍙 Korea'
# type = "select"
# rule = ['[]🍙 url-test', '(韩国.*0\.\d|KR.*0\.\d)']

[[custom_groups]]
name = '💥 ADban'
type = "select"
rule = ['[]REJECT', '[]☀️ DIRECT']

[[custom_groups]]
name = '☀️ DIRECT'
type = "select"
rule = ['[]DIRECT']

# [[custom_groups]]
# name = '🌐 Cloudflare'
# type = "select"
# rule = ['[]🌐 url-test', '([\w-]+WARP-\d*$)']

[[custom_groups]]
name = '🏘 HOME'
type = "select"
rule = ['[]DIRECT', '(Home.*)']

[[custom_groups]]
name = '🌹 url-test'
type = "url-test"
rule = ['^(?!.*自建\s+\|).*?(美国|USA).*?[x\d\)]$']
url = 'http://www.gstatic.com/generate_204'
interval = 400

# [[custom_groups]]
# name = '🍔 url-test'
# type = "url-test"
# rule = ['((?<!\|\s)美国.*0\.\d|(?<!\|\s)USA.*0\.\d)']
# url = 'http://www.gstatic.com/generate_204'
# interval = 400

[[custom_groups]]
name = '💐 url-test'
type = "url-test"
rule = ['^(?!.*自建\s+\|)(?!.*枫\s*\|\s*香港\s+HKBN\b).*?(香港|HK).*?[x\d\)]$']
url = 'http://www.gstatic.com/generate_204'
interval = 400

[[custom_groups]]
name = '🪻 url-test'
type = "url-test"
rule = ['^(?!.*自建\s+\|).*枫\s*\|\s*香港\s+HKBN\b.*?[x\d\)]$']
url = 'http://www.gstatic.com/generate_204'
interval = 400

# [[custom_groups]]
# name = '🥮 url-test'
# type = "url-test"
# rule = ['((?<!\|\s)香港.*0\.\d|(?<!\|\s)HK.*0\.\d)']
# url = 'http://www.gstatic.com/generate_204'
# interval = 400

# [[custom_groups]]
# name = '🍀 url-test'
# type = "url-test"
# rule = ['^(?!.*自建\s+\|).*?(台湾|TW).*?[x\d\)]$']
# url = 'http://www.gstatic.com/generate_204'
# interval = 400

# [[custom_groups]]
# name = '🥠 url-test'
# type = "url-test"
# rule = ['((?<!\|\s)台湾.*0\.\d|(?<!\|\s)TW.*0\.\d)']
# url = 'http://www.gstatic.com/generate_204'
# interval = 400

[[custom_groups]]
name = '🏵 url-test'
type = "url-test"
rule = ['^(?!.*自建\s+\|).*?(新加坡|SGP).*?[x\d\)]$']
url = 'http://www.gstatic.com/generate_204'
interval = 400

# [[custom_groups]]
# name = '🍛 url-test'
# type = "url-test"
# rule = ['((?<!\|\s)新加坡.*0\.\d|(?<!\|\s)SGP.*0\.\d)']
# url = 'http://www.gstatic.com/generate_204'
# interval = 400

[[custom_groups]]
name = '🌸 url-test'
type = "url-test"
rule = ['^(?!.*自建\s+\|).*?(日本|JP).*?[x\d\)]$']
url = 'http://www.gstatic.com/generate_204'
interval = 400

# [[custom_groups]]
# name = '🍣 url-test'
# type = "url-test"
# rule = ['((?<!\|\s)日本.*0\.\d|(?<!\|\s)JP.*0\.\d)']
# url = 'http://www.gstatic.com/generate_204'
# interval = 400

[[custom_groups]]
name = '🍉 url-test'
type = "url-test"
rule = ['^(?!.*自建\s+\|).*?(韩国|KR).*?[x\d\)]$']
url = 'http://www.gstatic.com/generate_204'
interval = 400

# [[custom_groups]]
# name = '🍙 url-test'
# type = "url-test"
# rule = ['((?<!\|\s)韩国.*0\.\d|(?<!\|\s)KR.*0\.\d)']
# url = 'http://www.gstatic.com/generate_204'
# interval = 400

# [[custom_groups]]
# name = '🌐 url-test'
# type = "url-test"
# rule = ['([\w-]+WARP-\d*$)']
# url = 'http://www.gstatic.com/generate_204'
# interval = 400
