# 风萧节点重命名规则
rename=^🇺🇸us.*-(.+?)-家宽(\d+).*@风萧 🇺🇸 US 家宽-0$2 $1
rename=^🇺🇸us.*-(.+?)-(\d+).*@风萧 🇺🇸 US-0$2 $1
rename=^🇺🇸us.*-(.+?)@.*@风萧 🇺🇸 US $1

rename=^🇭🇰HK.*-(.+?)-(\d+).*@风萧 🇭🇰 HK-0$2 $1
rename=^🇭🇰HK.*-(.+?)@.*@风萧 🇭🇰 HK $1

rename=^🇯🇵JP.*-(.+?)-(\d+).*@风萧 🇯🇵 JP-0$2 $1
rename=^🇯🇵JP.*-(.+?)@.*@风萧 🇯🇵 JP $1

rename=^🇨🇦CA.*-(.+?)-(\d+).*@风萧 🇨🇦 CA-0$2 $1
rename=^🇨🇦CA.*-(.+?)@.*@风萧 🇨🇦 CA $1

rename=^🇲🇩MD.*-(.+?)@.*@风萧 🇲🇩 MD $1
rename=^🇮🇳IN.*-(.+?)@.*@风萧 🇮🇳 IN $1
rename=^🇬🇧GB.*-(.+?)@.*@风萧 🇬🇧 GB $1
rename=^🇩🇪DE.*-(.+?)@.*@风萧 🇩🇪 DE $1

# 宝可梦节点重命名规则
rename=^🇭🇰【亚洲】香港(\d+)丨(.+?)【(.+?)】@宝可梦 🇭🇰 HK-$1 $2 $3
rename=^🇯🇵【亚洲】日本三网(\d+)丨(.+?)【(.+?)】@宝可梦 🇯🇵 JP-$1 三网 $2 $3
rename=^🇯🇵【亚洲】日本三期(\d+)丨(.+?)【(.+?)】@宝可梦 🇯🇵 JP-$1 三期 $2 $3
rename=^🇯🇵【亚洲】日本(\d+)丨(.+?)【(.+?)】@宝可梦 🇯🇵 JP-$1 $2 $3
rename=^🇺🇸【北美洲】美国(\d+)原生丨(.+?)【(.+?)】@宝可梦 🇺🇸 US-$1 原生 $2 $3
rename=^🇺🇸【北美洲】美国(\d+)丨(.+?)【(.+?)】@宝可梦 🇺🇸 US-$1 $2 $3
rename=^🇸🇬【亚洲】新加坡(\d+)丨(.+?)【(.+?)】@宝可梦 🇸🇬 SG-$1 $2 $3
rename=^🇹🇼【亚洲】台湾家宽(\d+)丨(.+?)【(.+?)】@宝可梦 🇹🇼 TW-$1 家宽 $2 $3
rename=^🇰🇷【亚洲】韩国家宽(\d+)丨(.+?)【(.+?)】@宝可梦 🇰🇷 KR-$1 家宽 $2 $3
