# 风萧节点重命名规则
rename=^🇺🇸us.*-(.+?)-家宽(\d+).*@风萧 🇺🇸 US 家宽-0$2 $1
rename=^🇺🇸us.*-(.+?)-(\d+).*@风萧 🇺🇸 US-0$2 $1
rename=^🇺🇸us.*-(.+?)@.*@风萧 🇺🇸 US $1

rename=^🇭🇰HK.*-(.+?)-(\d+).*@风萧 🇭🇰 HK-0$2 $1
rename=^🇭🇰HK.*-(.+?)@.*@风萧 🇭🇰 HK $1

rename=^🇯🇵JP.*-(.+?)-(\d+).*@风萧 🇯🇵 JP-0$2 $1
rename=^🇯🇵JP.*-(.+?)@.*@风萧 🇯🇵 JP $1

rename=^🇨🇦CA.*-(.+?)-(\d+).*@风萧 🇨🇦 CA-0$2 $1
rename=^🇨🇦CA.*-(.+?)@.*@风萧 🇨🇦 CA $1

rename=^🇲🇩MD.*-(.+?)@.*@风萧 🇲🇩 MD $1
rename=^🇮🇳IN.*-(.+?)@.*@风萧 🇮🇳 IN $1
rename=^🇬🇧GB.*-(.+?)@.*@风萧 🇬🇧 GB $1
rename=^🇩🇪DE.*-(.+?)@.*@风萧 🇩🇪 DE $1

# 宝可梦节点重命名规则
rename=^.*?】(.+?)(家宽)?\d+.*?([直连|专线|AWS|V6|IPLC]).*(\d+)倍$@宝可梦 $1$2 $3 $4x
rename=^hk.*?】(.+?)\d+.*?([直连|专线|AWS|V6|IPLC]).*(\d+)倍$@宝可梦 🇭🇰 $1 $2 $3x
rename=^jp.*?】(.+?)\d+.*?([直连|专线|AWS|V6|IPLC]).*(\d+)倍$@宝可梦 🇯🇵 $1 $2 $3x
rename=^us.*?】(.+?)\d+.*?([直连|专线|AWS|V6|IPLC]).*(\d+)倍$@宝可梦 🇺🇸 $1 $2 $3x
rename=^s[gs].*?】(.+?)\d+.*?([直连|专线|AWS|V6|IPLC]).*(\d+)倍$@宝可梦 🇸🇬 $1 $2 $3x
rename=^tw.*?】(.+?)\d+.*?([直连|专线|AWS|V6|IPLC]).*(\d+)倍$@宝可梦 🇹🇼 $1 $2 $3x
rename=^[ek]x.*?】(.+?)\d+.*?([直连|专线|AWS|V6|IPLC]).*(\d+)倍$@宝可梦 🇰🇷 $1 $2 $3x
